### ISSUE TITLE
Pretrain weights

### ISSUE THREAD

**Issue by n01z3** [bruinxiong/SENet.mxnet#1]
Thank you for code sharing! Could you please share current weights from imagenet? I plan to fine-tuning process on my task. So for my purpose none-final weights would be fine.

**Comment by bruinxiong** [comment]
@N01Z3 The training is ongoing because of GPU resources. Once I finish, I will upload the pretrained model. Thank you for your interest.

**Comment by bruinxiong** [comment]
@N01Z3 I have upload the pretrained model of SE-Resnext 50 on imagenet. Thank you for your interest.
