### ISSUE TITLE
any pretrain models?

### ISSUE THREAD

**Issue by enjoyyi00** [bruinxiong/SENet.mxnet#2]
any pretrain models?

**Comment by bruinxiong** [comment]
@iFighting Thank you for your interest. I will release the pre-trained model of Imagenet the following week. Please keep an eye on this. Thanks!

**Comment by bruinxiong** [comment]
@iFighting I have upload the pretrained model of SE-Resnext 50 on imagenet. Thank you for your interest.

**Comment by kli-casia** [comment]
有没有152层的模型参数。谢谢

**Comment by bruinxiong** [comment]
@kli-nlpr  目前没有足够的GPU资源来跑，但是有计划，就是时间会等得久一些。

**Comment by Sun-Fan** [comment]
你好，最近想做个关于针对se的实验对比，已经使用了该模型 the pretrained model of SE-Resnext 50 on imagenet，麻烦你可以提供一个没有加上SE的pretrain model  on imagenet吗
